---

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: create ssh directory
      become: yes
      file:
        path: "{{item}}"
        state: directory
        owner: root
        group: wheel
        mode: 0777
      with_items:
        - /etc/ssh

  roles:
    - profile-all
    - profile-dev
    - profile-dev-python
    - profile-dev-golang
    - profile-dev-ruby
    - profile-dev-node
    - profile-dev-java
