---

- hosts: 127.0.0.1
  connection: local

  tasks:
    - name: create ssh directory
      become: yes
      file:
        path: "{{item}}"
        state: directory
        owner: root
        group: wheel
        mode: 0777
      with_items:
        - /etc/ssh
    - name: personal ssh config
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh_config
    - name: personal ssh config in another location
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh/ssh_config
    - name: add to sudoers without password
      become: yes
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^pmdev', line: 'pmdev ALL=(ALL) NOPASSWD: ALL' }
    - name: install indiivudal apps via brew casks
      homebrew_cask: name={{item}} state=present
      with_items:
        - owncloud
        - lastpass

  roles:
    - profile-all
    - profile-consulting
    - profile-dev
    - profile-dev-python
    - profile-dev-aws

  vars:
    - computername: pmDev13
