---

- name: install general brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - curl

- name: install general cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - prezi
    - cord
    - transmit
    - owncloud
    - keepingyouawake
    - lastpass
    - pandoc
